# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0002_remove_program_semester_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2017-18', max_length=4)),
                ('is_supplementary_result', models.BooleanField(default=False)),
                ('is_revaluation_result', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='is_supplementary_result',
        ),
        migrations.AddField(
            model_name='program',
            name='semester_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='file_processor.Semester'),
        ),
        migrations.AddField(
            model_name='exam',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_processor.Document'),
        ),
        migrations.AddField(
            model_name='exam',
            name='semester_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='file_processor.Semester'),
        ),
        migrations.AddField(
            model_name='score',
            name='exam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='file_processor.Exam'),
        ),
    ]
